### ISSUE TITLE
Terminal bell / sound?

### ISSUE THREAD

**Issue by csuhta** [nocawy/D2R-IP-logger#1]
This script is amazing, thank you! The green text telling you when to make a new game is a lifesaver.

I'd like to suggest an option to also ring the terminal bell or play a reminder sound when the green text appears. I'm not sure how feasible that is on Windows 10/11 though

**Comment by nocawy** [comment]
Since the game creation cooldown is not constant anymore, I've reverted to displaying the number of seconds that has passes since the last game creation.
