### ISSUE TITLE
Option to freak out when you're on a target IP

### ISSUE THREAD

**Issue by csuhta** [nocawy/D2R-IP-logger#2]
Allow us to pass in an option where we are targeting a specific IP. When that shows up in the logs, print something like `!!! HOT !!!` in the log message next to the IP

**Comment by nocawy** [comment]
I'm considering this. But there already is another tool specifically written for DClone hunting, that does what you're asking for: https://github.com/VideoGameRoulette/D2RTools
Let me know if you'd still prefer this feature added here.

**Comment by csuhta** [comment]
@nocawy I also suggested it here because D2RTools is more of a TOS violation grey area than D2R IP Logger is right now

**Comment by nocawy** [comment]
This has been added in recent update. Hunted IP can be added as parameter in command line. When found, the IP will be displayed in red.
