### ISSUE TITLE
Can I not download few GBs of VB C++ tools to fix this error?

### ISSUE THREAD

**Issue by NiGHTsC** [nocawy/D2R-IP-logger#3]
or maybe I should just use your exe version...:sadge...
> C:\Windows\system32>pip install psutil
Collecting psutil
  Using cached psutil-5.8.0.tar.gz (470 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\NiGHTs\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NiGHTs\\AppData\\Local\\Temp\\pip-install-8xx9za3_\\psutil_a628273aec9047cc8e00f569bf450a6c\\setup.py'"'"'; __file__='"'"'C:\\Users\\NiGHTs\\AppData\\Local\\Temp\\pip-install-8xx9za3_\\psutil_a628273aec9047cc8e00f569bf450a6c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\NiGHTs\AppData\Local\Temp\pip-wheel-9fwo1c98'
       cwd: C:\Users\NiGHTs\AppData\Local\Temp\pip-install-8xx9za3_\psutil_a628273aec9047cc8e00f569bf450a6c\
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\psutil
  copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
  copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
  creating build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
  copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\NiGHTs\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NiGHTs\\AppData\\Local\\Temp\\pip-install-8xx9za3_\\psutil_a628273aec9047cc8e00f569bf450a6c\\setup.py'"'"'; __file__='"'"'C:\\Users\\NiGHTs\\AppData\\Local\\Temp\\pip-install-8xx9za3_\\psutil_a628273aec9047cc8e00f569bf450a6c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\NiGHTs\AppData\Local\Temp\pip-record-kaj6ewri\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\NiGHTs\AppData\Local\Programs\Python\Python310\Include\psutil'
         cwd: C:\Users\NiGHTs\AppData\Local\Temp\pip-install-8xx9za3_\psutil_a628273aec9047cc8e00f569bf450a6c\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
    creating build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
ERROR: Command errored out with exit status 1: 'C:\Users\NiGHTs\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NiGHTs\\AppData\\Local\\Temp\\pip-install-8xx9za3_\\psutil_a628273aec9047cc8e00f569bf450a6c\\setup.py'"'"'; __file__='"'"'C:\\Users\\NiGHTs\\AppData\\Local\\Temp\\pip-install-8xx9za3_\\psutil_a628273aec9047cc8e00f569bf450a6c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\NiGHTs\AppData\Local\Temp\pip-record-kaj6ewri\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\NiGHTs\AppData\Local\Programs\Python\Python310\Include\psutil' Check the logs for full command output.

**Comment by nocawy** [comment]
For now I don't know of any workaround.

It looks l like Microsoft Visual C++ 14.0 or greater is required to install psutil.
You can install it from: https://visualstudio.microsoft.com/visual-cpp-build-tools/
Or use the compiled D2R_ip.exe

**Comment by NiGHTsC** [comment]
yah, and that Visual Build tools wants you download whole SDKs+other packes for 2~6GBs...
meh...I'll just use your exe...

**Comment by Azotorp** [comment]
just uninstall it afterwards, the tools is just to build the pip library
select Desktop development with C++ as one of the packages.
also try cmd:
`%LocalAppData%\Programs\Python\Python310\python.exe -m pip install --upgrade pip`
